package org.xmlet.xsdasm.classes.infrastructure;

/**
 * Standard interface for every {@link Enum} class generated by the XsdAsmFaster solution.
 * @param <T> The type of data enumerated by the {@link Enum} class.
 */
public interface EnumInterface<T> {

    T getValue();

}
